---
## Tenant Application Subnets start at 192.168.10.0/24
## /24 is provided for each application tier (3 total)
## Tenant Routing subnets start at 10.0.0.0/30
## /30 is provided for each routing subnet (2 total)

########## Update for new Tenants #############

tenants:
  tenant1:
    name: Company XYZ
    subnets:
      web: 192.168.10.0/24
      app: 192.168.11.0/24
      db: 192.168.12.0/24
      edge: 10.0.0.0/30
      shared: 10.0.0.4/30

###############################################

shared_services:
  - name: backup
    network: 172.16.20.0/24
    port: 443
    type: tcp
  - name: dns
    network: 172.16.21.254/32
    port: 53
    type: udp
  - name: snmp
    network: 172.16.21.0/24
    port: 161 162
    type: udp

provider:
  username: arista
  password: arista
  host: "{{ inventory_ip }}"
  transport: eapi
  use_ssl: no
  authorize: yes
  port: "{{ inventory_port }}"

