---
########## Update for new Tenants #############

vrfs:
  - tenant: tenant1
    rd: "11:11"

acls:
  - tenant: tenant1
    name: web
  - tenant: tenant1
    name: app
  - tenant: tenant1
    name: db
  - tenant: tenant1
    name: shared

route_maps:
  - tenant: tenant1
    name: edge-ingress
  - tenant: tenant1
    name: shared-ingress

prefix_lists:
  - tenant: tenant1
    name: edge-ingress
  - tenant: tenant1
    name: shared-ingress

#############################################



