---

########## Update for new Tenants #############

edge_vlans:
  - tenant: tenant1
    number: 13
    name: edge
    vni: 10013
  - tenant: tenant2
    number: 18
    name: edge
    vni: 10018

###############################################
