---
########## Update for new Tenants #############

vrfs:
  - tenant: tenant1
    rd: "11:11"

acls:
  - tenant: tenant1
    name: web
    rules:
      - action: permit
        type: tcp
        src: "{{ tenants['tenant1']['subnets']['web'] }}"
        src_port: 443
        dst: "{{ tenants['tenant1']['subnets']['db'] }}"
        dst_port: 1433
  - tenant: tenant1
    name: app
  - tenant: tenant1
    name: db
    rules:
      - action: permit
        type: tcp
        src: "{{ tenants['tenant1']['subnets']['db'] }}"
        src_port: 1433
        dst: "{{ tenants['tenant1']['subnets']['web'] }}"
        dst_port: 443
  - tenant: tenant1
    name: shared

route_maps:
  - tenant: tenant1
    name: edge-ingress
  - tenant: tenant1
    name: shared-ingress

prefix_lists:
  - tenant: tenant1
    name: edge-ingress
  - tenant: tenant1
    name: shared-ingress

#############################################



