---
########## Update for new Tenants #############

vrfs:
  - tenant: tenant1
    rd: "11:11"
  - tenant: tenant2
    rd: "22:22"

acls:
  - tenant: tenant1
    name: web
    rules:
      - action: permit
        type: tcp
        src: "{{ tenants['tenant1']['subnets']['web'] }}"
        src_port: 443
        dst: "{{ tenants['tenant1']['subnets']['db'] }}"
        dst_port: 1433
  - tenant: tenant1
    name: app
  - tenant: tenant1
    name: db
    rules:
      - action: permit
        type: tcp
        src: "{{ tenants['tenant1']['subnets']['db'] }}"
        src_port: 1433
        dst: "{{ tenants['tenant1']['subnets']['web'] }}"
        dst_port: 443
  - tenant: tenant1
    name: shared
  - tenant: tenant2
    name: web
  - tenant: tenant2
    name: app
  - tenant: tenant2
    name: db
    
#############################################

route_maps:
  - name: edge-ingress
    sequences:
      - number: 10
        action: permit
        match: edge-prefixes
  - name: shared-ingress
    sequences:
      - number: 10
        action: permit
        match: shared-prefixes

prefix_lists:
  - name: edge-prefixes
    sequences:
      - number: 10
        network: 0.0.0.0/0
      - number: 20
        network: 8.8.8.8/32
  - name: shared-prefixes
    sequences:
      - number: 10
        network: 172.16.20.0/24
      - number: 20
        network: 172.16.21.0/24

