---
## Playbook to build configuration for tenant routing

- name: Build all tenants routing configurations
  hosts: all
  gather_facts: no
  connection: local

  roles:
    - interfaces
    - vlans-vni
    - routing
    - acls
  
  post_tasks:
    - name: Assemble static configlets to build folder
      assemble:
        src: "configs/{{ inventory_hostname }}/static/"
        dest: "configs/{{ inventory_hostname }}/build/z-assembled-static.cfg"

    - name: Assemble configlet snippets for all devices
      assemble:
        src: "configs/{{ inventory_hostname }}/build/"
        dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}.cfg"
