---

- name: Build physical interface configuration
  template: 
    src: physical.j2
    dest: "configs/{{ inventory_hostname }}/build/d-physical.cfg"
  when: phy_interfaces is defined

- name: Build loopback interface configurations
  template:
    src: loopbacks.j2
    dest: "configs/{{ inventory_hostname }}/build/e-loopbacks.cfg"
  when: loopbacks is defined

- name: Build SVI configurations
  template:
    src: svis.j2
    dest: "configs/{{ inventory_hostname }}/build/f-svis.cfg"
  when: svis is defined
