---

- name: Build VRF configuration
  template: 
    src: vrf.j2
    dest: "configs/{{ inventory_hostname }}/build/a-vrf.cfg"
  when: vrfs is defined

- name: Build BGP configuration
  template:
    src: bgp.j2
    dest: "configs/{{ inventory_hostname }}/build/j-bgp.cfg"
  when: bgp is defined

- name: Build prefix-list configuration
  template:
    src: prefix-lists.j2
    dest: "configs/{{ inventory_hostname }}/build/k-prefixlists.cfg"
  when: prefix_lists is defined

- name: Build route-map configuration
  template:
    src: route-maps.j2
    dest: "configs/{{ inventory_hostname }}/build/l-routemaps.cfg"
  when: route_maps is defined
