---
phy_interfaces:
  - name: Ethernet1
    description: server1-eth0
    mode: trunk
  - name: Ethernet2
    description: spine1-eth3
    mode: routed
    ip_addr: 10.1.0.9/30

loopbacks:
  - name: Loopback0
    description: router-id
    ip_addr: 3.3.3.3/32
  - name: Loopback1
    description: vxlan-source-int
    ip_addr: 33.33.33.33/32

bgp:
  local_as: 65003
  router_id: 3.3.3.3
  neighbors:
    - ip_addr: 10.1.0.10
      as: 65000
  networks:
    - subnet: 3.3.3.3/32
    - subnet: 33.33.33.33/32
